export const locations = [
  {
    country: "Spain",
    regions: [
      "A Coruña",
      "Albacete",
      "Alicante/Alacant",
      "Almería",
      "Araba/Álava",
      "Asturias",
      "Badajoz",
      "Barcelona",
      "Bizkaia",
      "Burgos",
      "Cantabria",
      "Castellón/Castelló",
      "Ceuta",
      "Ciudad Real",
      "Cuenca",
      "Cáceres",
      "Cádiz",
      "Córdoba",
      "Gipuzkoa",
      "Girona",
      "Granada",
      "Guadalajara",
      "Huelva",
      "Huesca",
      "Islas Baleares",
      "Jaén",
      "León",
      "Lleida",
      "Lugo",
      "Madrid",
      "Melilla",
      "Murcia",
      "Málaga",
      "Navarra",
      "Ourense",
      "Palencia",
      "Palmas, Las",
      "Pontevedra",
      "Rioja, La",
      "Salamanca",
      "Santa Cruz de Tenerife",
      "Segovia",
      "Sevilla",
      "Soria",
      "Tarragona",
      "Teruel",
      "Toledo",
      "Valencia",
      "Valladolid",
      "Zamora",
      "Zaragoza",
      "Ávila"
    ]
  },
  {
    country: "France",
    regions: [
      "Ain",
      "Aube",
      "Aude",
      "Aveyron",
      "Bouches du Rhône",
      "Calvados",
      "Cantal",
      "Charente",
      "Charente Maritime",
      "Cher",
      "Corrèze",
      "Aisne",
      "Côte d'Or",
      "Côtes d'Armor",
      "Creuse",
      "Dordogne",
      "Doubs",
      "Drôme",
      "Eure",
      "Eure-et-Loir",
      "Finistère",
      "Corse du Sud",
      "Haute-Corse",
      "Allier",
      "Gard",
      "Haute-Garonne",
      "Gers",
      "Gironde",
      "Hérault",
      "Ille-et-Vilaine",
      "Indre",
      "Indre-et-Loire",
      "Isère",
      "Jura",
      "Alpes de Haute-Provence",
      "Landes",
      "Loir-et-Cher",
      "Loire",
      "Haute-Loire",
      "Loire-Atlantique",
      "Loiret",
      "Lot",
      "Lot-et-Garonne",
      "Lozère",
      "Maine-et-Loire",
      "Hautes-Alpes",
      "Manche",
      "Marne",
      "Haute-Marne",
      "Mayenne",
      "Meurthe-et-Moselle",
      "Meuse",
      "Morbihan",
      "Moselle",
      "Nièvre",
      "Nord",
      "Alpes-Maritimes",
      "Oise",
      "Orne",
      "Pas-de-Calais",
      "Puy-de-Dôme",
      "Pyrénées-Atlantiques",
      "Hautes-Pyrénées",
      "Pyrénées-Orientales",
      "Bas-Rhin",
      "Haut-Rhin",
      "Rhône",
      "Ardèche",
      "Haute-Saône",
      "Saône-et-Loire",
      "Sarthe",
      "Savoie",
      "Haute-Savoie",
      "Paris",
      "Seine-Maritime",
      "Seine-et-Marne",
      "Yvelines",
      "Deux-Sèvres",
      "Ardennes",
      "Somme",
      "Tarn",
      "Tarn-et-Garonne",
      "Var",
      "Vaucluse",
      "Vendée",
      "Vienne",
      "Haute-Vienne",
      "Vosges",
      "Yonne",
      "Ariège",
      "Territoire de Belfort",
      "Essonne",
      "Hauts-de-Seine",
      "Seine-Saint-Denis",
      "Val-de-Marne",
      "Val-d’Oise",
      "Guadeloupe",
      "Martinique",
      "Guyane française",
      "La Réunion",
      "Mayotte"
    ]
  },
  {
    country: "Italy",
    regions: [
      "Piemonte",
      "Valle d'Aosta",
      "Lombardia",
      "Trentino-Alto Adige",
      "Veneto",
      "Friuli-Venezia Giulia",
      "Liguria",
      "Emilia-Romagna",
      "Toscana",
      "Umbria",
      "Marche",
      "Lazio",
      "Abruzzo",
      "Molise",
      "Campania",
      "Puglia",
      "Basilicata",
      "Calabria",
      "Sicilia",
      "Sardegna"
    ]
  },
  {
    country: "Netherlands & Belgium",
    regions: [
      "Groningen",
      "Friesland",
      "Drenthe",
      "Overijssel",
      "Flevoland",
      "Gelderland",
      "Utrecht",
      "Noord-Holland",
      "Zuid-Holland",
      "Zeeland",
      "Noord-Brabant",
      "Limburg",
      "Antwerpen",
      "Limburg (België)",
      "Oost-Vlaanderen",
      "Vlaams-Brabant",
      "West-Vlaanderen",
      "Brussel"
    ]
  },
  {
    country: "Switzerland",
    regions: [
      "Argovie - Aargau",
      "Appenzell Rhodes intérieures - Inner-Rhoden",
      "Appenzell Rhodes extérieures - Ausser-Rhoden",
      "Berne - Bern",
      "Bâle Campagne - Basel Land",
      "Bâle Ville - Basel Stadt",
      "Fribourg - Freiburg",
      "Genève - Genf",
      "Glaris - Glarus",
      "Grisons - Graubuenden",
      "Jura",
      "Lucerne - Luzern",
      "Neuchâtel - Neuenburg",
      "Nidwald - Nidwalden",
      "Obwald - Obwalden",
      "Saint-Gall - Sankt Gallen",
      "Schaffhouse - Schaffhausen",
      "Soleure - Solothurn",
      "Schwyz",
      "Thurgovie - Thurgau",
      "Ticino - Tessin",
      "Uri",
      "Vaud - Waadt",
      "Valais - Vallis",
      "Zug",
      "Zurich - Zürich"
    ]
  },
  {
    country: "Germany",
    regions: [
      "Baden-Württemberg",
      "Bayern",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hessen",
      "Mecklenburg-Vorpommern",
      "Niedersachsen",
      "Nordrhein-Westfalen",
      "Rheinland-Pfalz",
      "Saarland",
      "Sachsen",
      "Sachsen-Anhalt",
      "Schleswig-Holstein",
      "Thüringen"
    ]
  },
  {
    country: "Portugal",
    regions: [
      "Aveiro",
      "Beja",
      "Braga",
      "Bragança",
      "Castelo Branco",
      "Coimbra",
      "Évora",
      "Faro",
      "Guarda",
      "Leiria",
      "Lisboa",
      "Madeira",
      "Portalegre",
      "Porto",
      "Santarém",
      "Setúbal",
      "Viana do Castelo",
      "Vila Real",
      "Viseu"
    ]
  },
  {
    country: "Norway",
    regions: [
      "Alesund",
      "Arendal",
      "Bergen",
      "Bodo",
      "Drammen",
      "Egersund",
      "Farsund",
      "Flekkefjord",
      "Floro",
      "Fredrikstad",
      "Gjovik",
      "Grimstad",
      "Halden",
      "Hamar",
      "Hammerfest",
      "Harstad",
      "Haugesund",
      "Holmestrand",
      "Honefoss",
      "Horten",
      "Kongsberg",
      "Kongsvinger",
      "Kristiansand",
      "Kristiansund",
      "Larvik",
      "Lillehammer",
      "Mandal",
      "Molde",
      "Moss",
      "Namsos",
      "Narvik",
      "Notodden",
      "Oslo",
      "Porsgrunn",
      "Risor",
      "Sandefjord",
      "Sandnes",
      "Sarpsborg",
      "Skien",
      "Sogne",
      "Stavanger",
      "Steinkjer",
      "Tonsberg",
      "Tromso",
      "Trondheim",
      "Vadso",
      "Vardo",
      "Vennesla"
    ]
  }
]
